# Generated by Django 5.1.6 on 2025-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
